"""Initialisation du module prompts."""

from prompts.diodes import PROMPT_DIODE_SIMPLE, PROMPT_DIODE_BOITES
from prompts.diode_zener import PROMPT_DIODE_ZENER_SIMPLE
from prompts.transistor import PROMPT_TRANSISTOR_BIPOLAIRE, PROMPT_INVERSEUR_BIPOLAIRE
from prompts.passive import (
    PROMPT_DIVISEUR_TENSION,
    PROMPT_PREMIER_ORDRE_PASSE_BAS,
    PROMPT_PREMIER_ORDRE_SIGNAL_CARRE,
    PROMPT_PREMIER_ORDRE_SIGNAL_CARRE_CRETE,
    PROMPT_THEVENIN_RC_SIGNAL_CARRE,
    PROMPT_PUISSANCE_SERIE,
    PROMPT_PUISSANCE_PARALLELE,
    PROMPT_PUISSANCE_DEUX_SOURCES,
)
from prompts.general import PROMPT_GENERAL

__all__ = [
    "PROMPT_DIODE_SIMPLE",
    "PROMPT_DIODE_BOITES",
    "PROMPT_DIODE_ZENER_SIMPLE",
    "PROMPT_TRANSISTOR_BIPOLAIRE",
    "PROMPT_INVERSEUR_BIPOLAIRE",
    "PROMPT_DIVISEUR_TENSION",
    "PROMPT_PREMIER_ORDRE_PASSE_BAS",
    "PROMPT_PREMIER_ORDRE_SIGNAL_CARRE",
    "PROMPT_PREMIER_ORDRE_SIGNAL_CARRE_CRETE",
    "PROMPT_THEVENIN_RC_SIGNAL_CARRE",
    "PROMPT_PUISSANCE_SERIE",
    "PROMPT_PUISSANCE_PARALLELE",
    "PROMPT_PUISSANCE_DEUX_SOURCES",
    "PROMPT_GENERAL"
]
